[package]
name = "helgobox-artwork-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = { version = "0.36.0", features = ["png"] }
anyhow.workspace = true