[package]
name = "realearn-api"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"
publish = false

[features]
default = []
playtime = ["dep:playtime-api"]

[dependencies]
# For being able to use the API macro
realearn-macros.workspace = true
reaper-low.workspace = true
serde.workspace = true
semver.workspace = true
serde_json.workspace = true
playtime-api = { workspace = true, optional = true }
derive_more.workspace = true
enum-iterator.workspace = true
num_enum.workspace = true
enum-map.workspace = true
enumset = { workspace = true, features = ["serde", "alloc"]}

[dev-dependencies]
mlua.workspace = true